# Generated by Django 4.2.2 on 2023-06-22 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('c_genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('p_titulo', models.CharField(max_length=100)),
                ('p_precio', models.IntegerField()),
                ('p_des', models.CharField(max_length=50)),
                ('p_desc', models.CharField(max_length=1000)),
                ('p_stock', models.IntegerField()),
                ('p_img', models.ImageField(upload_to='img_prod')),
                ('p_fecha', models.DateField(auto_now_add=True)),
                ('id_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.genero')),
            ],
        ),
    ]
