# Generated by Django 4.2.2 on 2023-07-08 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('c_plataforma', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.plataforma'),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
